### ISSUE TITLE
Your base layout misses html, head, body tags

### ISSUE THREAD

**Issue by daniel-j-h** [blaringsilence/pegasus#17]
It seems like your base layout is missing

```
<html>
    ..
    <head>
        ..
    </head>
    ..
    <body>
        ..
    </body>
    ..
</html>
```

https://github.com/blaringsilence/pegasus/blob/f700e963091166ed293394ef1f2c0a80ea5e6613/pegasus/templates/layout.html

**Comment by mariamrf** [comment]
I was under the impression they were [optional](http://www.w3schools.com/html/html_head.asp)? But apparently [IE has a problem with it](http://stackoverflow.com/questions/5641997/is-it-necessary-to-write-head-body-and-html-tags). Alright :+1:
